name: Scrape latest data

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # once an hour at 5 minutes past
    - cron: "5 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch latest data
        run: |-
          curl https://public.tableau.com/views/OregonCOVID-19TestingandOutcomesbyCounty-SummaryTable/CasesandTestingbyCountySummaryTable.csv?:showVizHome=no > county.csv
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
