name: Scrape latest data

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # once an hour at 5 minutes past
    - cron: "5 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch latest data
        run: |-
          curl https://public.tableau.com/vizql/w/OregonCOVID-19TestingandOutcomesbyCounty-SummaryTable/v/CasesandTestingbyCountySummaryTable/vudcsv/sessions/C449C397902C4606A685A58336C138CC-0:0/views/5983853632179391212_17505078358919484414?summary=true > county.csv
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
